name: Claude Code Assistant

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened, labeled]

jobs:
  claude:
    # @claude 멘션이 있거나 PR 이벤트일 때 실행
    if: |
      github.event_name == 'pull_request' || 
      contains(github.event.comment.body, '@claude') ||
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'claude'))
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      issues: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Run Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
```

5. **커밋**
   - Commit message: `Add Claude GitHub Action workflow`
   - "Commit directly to the main branch" 선택
   - "Commit changes" 클릭

### Step 5: 설치 확인

1. **Actions 탭 확인**
   - https://github.com/kimbj0214-ship-it/claude/actions
   - "Claude Code Assistant" 워크플로우가 보이면 성공

2. **Secrets 확인**
   - https://github.com/kimbj0214-ship-it/claude/settings/secrets/actions
   - `ANTHROPIC_API_KEY`가 목록에 있으면 성공

3. **GitHub 앱 확인**
   - https://github.com/settings/installations
   - "Claude" 앱이 설치되어 있으면 성공

## 테스트하기

### 간단한 테스트: Issue 생성

1. **Issue 생성**
   - https://github.com/kimbj0214-ship-it/claude/issues/new
   - 제목: "Claude 테스트"
   - 내용:
```
     @claude 안녕하세요! 
     
     이 리포지토리에 대해 간단히 설명해주세요.
